apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazing
  labels:
    kubectl.kubernetes.io/name: amazing
    apps.joey.io/name: amazing
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      apps.joey.io/name: amazing
  template:
    metadata:
      labels:
        apps.joey.io/name: amazing
    spec:
      containers:
      - name: amazing
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}

