apiVersion: v1
kind: Service
metadata:
  name: amazing
  labels:
     apps.joey.io/name: amazing
spec:
  type: {{ .Values.service.type }}
  selector:
    apps.joey.io/name: amazing
  ports:
  - name: port
    protocol: TCP
    targetPort: {{ .Values.service.port }}
    port: {{ .Values.service.port }}


