replicaCount: 2

image:
  repository: joeyrah/joey-rahman-sre-exercise
  tag: latest
  pullPolicy: Always

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"


service:
  type: ClusterIP
  port: 80

ingress:
  host: https-example.foo.com

